#==========================================================================
# Description: Compile the kernel
# Copyright (C) 2021 https://github.com/unifreq/openwrt_packit
# Copyright (C) 2021 https://github.com/ophub/amlogic-s9xxx-armbian
#==========================================================================

name: Compile the kernel

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      kernel_source:
        description: "Select the kernel source"
        required: false
        default: "unifreq"
        type: choice
        options:
          - unifreq
      kernel_version:
        description: "Select kernel version"
        required: false
        default: "5.4.1_5.10.1"
        type: choice
        options:
          - 5.4.1_5.10.1
          - 5.15.1_6.1.1
          - 5.4.1
          - 5.4.237
          - 5.4.238
          - 5.4.239
          - 5.4.240
          - 5.4.241
          - 5.4.242
          - 5.4.243
          - 5.4.244
          - 5.4.245
          - 5.4.246
          - 5.4.247
          - 5.4.248
          - 5.10.1
          - 5.10.175
          - 5.10.176
          - 5.10.177
          - 5.10.178
          - 5.10.179
          - 5.10.180
          - 5.10.181
          - 5.10.182
          - 5.10.183
          - 5.10.184
          - 5.10.185
          - 5.15.1
          - 5.15.103
          - 5.15.104
          - 5.15.105
          - 5.15.106
          - 5.15.107
          - 5.15.108
          - 5.15.109
          - 5.15.110
          - 5.15.111
          - 5.15.112
          - 5.15.113
          - 5.15.114
          - 5.15.115
          - 5.15.116
          - 5.15.117
          - 5.15.118
          - 6.1.1
          - 6.1.20
          - 6.1.21
          - 6.1.22
          - 6.1.23
          - 6.1.24
          - 6.1.25
          - 6.1.26
          - 6.1.27
          - 6.1.28
          - 6.1.29
          - 6.1.30
          - 6.1.31
          - 6.1.32
          - 6.1.33
          - 6.1.34
          - 6.1.35
      kernel_auto:
        description: "Auto use the latest kernel"
        required: false
        default: true
        type: boolean
      kernel_package:
        description: "Select compile package list"
        required: false
        default: "all"
        type: choice
        options:
          - all
          - dtbs
      kernel_toolchain:
        description: "Select the compilation toolchain"
        required: false
        default: "gcc"
        type: choice
        options:
          - clang
          - gcc
      kernel_sign:
        description: "Set the kernel custom signature"
        required: false
        default: "-arf.prsty_"
        type: choice
        options:
          - -ophub
          - -arf.prsty_

env:
  TZ: America/New_York

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialization environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          [[ -n "${AGENT_TOOLSDIRECTORY}" ]] && sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
          sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d /usr/local/lib/android 2>/dev/null
          sudo -E apt-get -y update
          sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
          sudo -E apt-get -y install $(curl -fsSL https://is.gd/depend_ubuntu2204_armbian)
          sudo -E systemctl daemon-reload
          #sudo -E apt-get -y full-upgrade
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          sudo timedatectl set-timezone "${TZ}"
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Compile the kernel [ ${{ inputs.kernel_version }} ]
        uses: arfprsty810/amlogic-s9xxx-armbian@main
        if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
        with:
          build_target: kernel
          kernel_source: ${{ inputs.kernel_source }}
          kernel_version: ${{ inputs.kernel_version }}
          kernel_auto: ${{ inputs.kernel_auto }}
          kernel_package: ${{ inputs.kernel_package }}
          kernel_sign: ${{ inputs.kernel_sign }}
          kernel_toolchain: ${{ inputs.kernel_toolchain }}

      - name: Upload Kernel to Release
        uses: ncipollo/release-action@main
        if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
        with:
          tag: kernel_stable
          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
          allowUpdates: true
          token: ${{ secrets.GH_TOKEN }}
          body: |
            The kernel can be used to compile Armbian and OpenWrt.
            The kernel source code comes from: ${{ inputs.kernel_source }}
            The kernel compilation toolchain: ${{ inputs.kernel_toolchain }}
